### ISSUE TITLE
Add feature config

### ISSUE THREAD

**Issue by ak9024** [ak9024/rustywatch#6]
## Problem
Currently to running `rustywatch` need to add more command options, so it takes a lot of efforts.

## Solution
Need to add file configuration such as `.rustywatch.yaml` with contents.

```yaml
dir: .
cmd: 'go build main.go'
bin_path: './main'
bin_arg:
  - server
  - log
ignore:
  - '.git'
  - '.exe'
  - '.DS_Store'
```
